services:
  web:
    env_file:
      - tokens.env
    build:
      context: .
      target: app-build
    ports:
      - "8080:8080"
    volumes:
      - data-storage:/data
    command: [
      "bash", "-c", "uvicorn src.main.web:create_app --host 0.0.0.0  --port 8080 --log-level info"
    ]
volumes:
  data-storage: {}